# Generated by Django 3.2.5 on 2022-06-08 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Petparent',
            fields=[
                ('pp_id', models.IntegerField(max_length=50, primary_key='True', serialize=False)),
                ('name', models.CharField(max_length=70)),
                ('email_id', models.EmailField(max_length=100)),
                ('phone_number', models.IntegerField(max_length=10)),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('pin', models.CharField(max_length=6)),
            ],
        ),
    ]
