# Generated by Django 3.2.5 on 2022-06-15 10:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Grooming',
            fields=[
                ('grooming_id', models.IntegerField(primary_key='True', serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('desc', models.CharField(max_length=100)),
                ('fees', models.IntegerField()),
                ('image', models.ImageField(default='', upload_to='grooming')),
            ],
        ),
        migrations.CreateModel(
            name='PetParent',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('phone_number', models.CharField(max_length=10, unique='True')),
                ('address', models.CharField(blank='True', max_length=100, null='True')),
                ('pin', models.CharField(blank='True', max_length=6, null='True')),
            ],
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('provider_id', models.IntegerField(primary_key='True', serialize=False)),
                ('name', models.CharField(max_length=70)),
                ('email_id', models.EmailField(max_length=100, unique='True')),
                ('phone_number', models.CharField(max_length=10, unique='True')),
                ('address', models.CharField(blank='True', max_length=100, null='True')),
                ('city', models.CharField(blank='True', max_length=50, null='True')),
                ('pin', models.CharField(blank='True', max_length=6, null='True')),
                ('status', models.CharField(choices=[('Not Verified', 'Not Verified'), ('Verified', 'Verified'), ('Inactive', 'Inactive')], default='Not Verified', max_length=100)),
                ('image', models.ImageField(default='', upload_to='provider')),
            ],
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('training_id', models.IntegerField(primary_key='True', serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('desc', models.CharField(max_length=100)),
                ('fees', models.IntegerField()),
                ('image', models.ImageField(default='', upload_to='training')),
            ],
        ),
        migrations.CreateModel(
            name='Vet',
            fields=[
                ('vet_id', models.IntegerField(primary_key='True', serialize=False)),
                ('name', models.CharField(max_length=70)),
                ('email_id', models.EmailField(max_length=100, unique='True')),
                ('phone_number', models.CharField(max_length=10, unique='True')),
                ('address', models.CharField(blank='True', max_length=100, null='True')),
                ('city', models.CharField(blank='True', max_length=50, null='True')),
                ('pin', models.CharField(blank='True', max_length=6, null='True')),
                ('status', models.CharField(choices=[('Not Verified', 'Not Verified'), ('Verified', 'Verified'), ('Inactive', 'Inactive')], default='Not Verified', max_length=20)),
                ('fees', models.IntegerField()),
                ('image', models.ImageField(default='', upload_to='vet')),
            ],
        ),
        migrations.CreateModel(
            name='VetBooking',
            fields=[
                ('booking_id', models.IntegerField(primary_key='True', serialize=False)),
                ('pet_name', models.CharField(max_length=50)),
                ('pet_type', models.CharField(max_length=50)),
                ('pet_breed', models.CharField(max_length=50)),
                ('illness_details', models.CharField(max_length=100)),
                ('appo_date_time', models.DateTimeField()),
                ('appo_full_date_time', models.DateTimeField()),
                ('appo_status', models.CharField(choices=[('Registered', 'Registered'), ('Confirmed', 'Confirmed'), ('Fullfilled', 'Fullfilled')], default='Registered', max_length=100)),
                ('pp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vet_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.vet')),
            ],
        ),
        migrations.CreateModel(
            name='TrainingBooking',
            fields=[
                ('booking_id', models.IntegerField(primary_key='True', serialize=False)),
                ('pet_name', models.CharField(blank='True', max_length=50, null='True')),
                ('pet_type', models.CharField(max_length=50)),
                ('pet_breed', models.CharField(blank='True', max_length=50, null='True')),
                ('appo_date_time', models.DateTimeField()),
                ('appo_full_date_time', models.DateTimeField()),
                ('appo_status', models.CharField(choices=[('Registered', 'Registered'), ('Confirmed', 'Confirmed'), ('Fullfilled', 'Fullfilled')], default='Registered', max_length=100)),
                ('pp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('provider_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.provider')),
                ('training_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.training')),
            ],
        ),
        migrations.CreateModel(
            name='GroomingBooking',
            fields=[
                ('booking_id', models.IntegerField(primary_key='True', serialize=False)),
                ('pet_name', models.CharField(blank='True', max_length=50, null='True')),
                ('pet_type', models.CharField(max_length=50)),
                ('pet_breed', models.CharField(blank='True', max_length=50, null='True')),
                ('appo_date_time', models.DateTimeField()),
                ('appo_full_date_time', models.DateTimeField()),
                ('appo_status', models.CharField(choices=[('Registered', 'Registered'), ('Confirmed', 'Confirmed'), ('Fullfilled', 'Fullfilled')], default='Registered', max_length=100)),
                ('grooming_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.grooming')),
                ('pp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('provider_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.provider')),
            ],
        ),
    ]
