# Generated by Django 3.2.5 on 2022-06-15 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groomingbooking',
            name='pp_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.petparent'),
        ),
        migrations.AlterField(
            model_name='trainingbooking',
            name='pp_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.petparent'),
        ),
        migrations.AlterField(
            model_name='vetbooking',
            name='pp_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.petparent'),
        ),
    ]
