# Generated by Django 3.2.5 on 2022-06-08 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petparent',
            name='phone_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='petparent',
            name='pp_id',
            field=models.IntegerField(primary_key='True', serialize=False),
        ),
    ]
