# Generated by Django 3.2.5 on 2022-06-08 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20220609_0124'),
    ]

    operations = [
        migrations.CreateModel(
            name='Groomer',
            fields=[
                ('groomer_id', models.IntegerField(primary_key='True', serialize=False)),
                ('name', models.CharField(max_length=70)),
                ('email_id', models.EmailField(max_length=100)),
                ('phone_number', models.IntegerField()),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('pin', models.CharField(max_length=6)),
                ('status', models.CharField(choices=[('Not Verified', 'Not Verified'), ('Verified', 'Verified'), ('Inactive', 'Inactive')], default='Not Verified', max_length=100)),
            ],
        ),
    ]
