# Generated by Django 3.2.5 on 2022-06-08 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_groomer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vet',
            fields=[
                ('vet_id', models.IntegerField(primary_key='True', serialize=False)),
                ('name', models.CharField(max_length=70)),
                ('email_id', models.EmailField(max_length=100)),
                ('phone_number', models.IntegerField()),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('pin', models.CharField(max_length=6)),
                ('status', models.CharField(choices=[('Not Verified', 'Not Verified'), ('Verified', 'Verified'), ('Inactive', 'Inactive')], default='Not Verified', max_length=20)),
                ('fees', models.IntegerField(max_length=4)),
            ],
        ),
    ]
