# Generated by Django 3.2.5 on 2022-06-16 19:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0004_auto_20220617_0051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groomingbooking',
            name='grooming_id',
            field=models.ForeignKey(blank='True', null='True', on_delete=django.db.models.deletion.CASCADE, to='main_app.grooming'),
        ),
        migrations.AlterField(
            model_name='trainingbooking',
            name='provider_id',
            field=models.ForeignKey(blank='True', null='True', on_delete=django.db.models.deletion.CASCADE, to='main_app.provider'),
        ),
        migrations.AlterField(
            model_name='vetbooking',
            name='pp_id',
            field=models.ForeignKey(blank='True', null='True', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
