# Generated by Django 3.2.5 on 2022-06-08 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_vet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vet',
            name='fees',
            field=models.IntegerField(),
        ),
    ]
