# Generated by Django 3.2.5 on 2022-06-16 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_auto_20220617_0127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vetbooking',
            name='appo_full_date_time',
            field=models.DateTimeField(blank='True', null='True'),
        ),
    ]
