# Generated by Django 3.2.5 on 2022-06-08 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_services'),
    ]

    operations = [
        migrations.CreateModel(
            name='VetBooking',
            fields=[
                ('booking_id', models.IntegerField(primary_key='True', serialize=False)),
                ('pet_name', models.CharField(max_length=50)),
                ('pet_type', models.CharField(max_length=50)),
                ('pet_breed', models.CharField(max_length=50)),
                ('illness_details', models.CharField(max_length=100)),
                ('appo_date_time', models.DateTimeField()),
                ('appo_full_date_time', models.DateTimeField()),
                ('appo_status', models.CharField(max_length=15)),
                ('pp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.petparent')),
                ('vet_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.vet')),
            ],
        ),
    ]
