# Generated by Django 3.2.5 on 2022-06-15 05:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0008_servicebooking'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grooming',
            fields=[
                ('grooming_id', models.IntegerField(primary_key='True', serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('desc', models.CharField(max_length=100)),
                ('fees', models.IntegerField()),
                ('image', models.ImageField(default='', upload_to='grooming')),
            ],
        ),
        migrations.CreateModel(
            name='GroomingBooking',
            fields=[
                ('booking_id', models.IntegerField(primary_key='True', serialize=False)),
                ('pet_name', models.CharField(max_length=50)),
                ('pet_type', models.CharField(max_length=50)),
                ('pet_breed', models.CharField(max_length=50)),
                ('appo_date_time', models.DateTimeField()),
                ('appo_full_date_time', models.DateTimeField()),
                ('appo_status', models.CharField(max_length=15)),
                ('grooming_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.grooming')),
                ('pp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('provider_id', models.IntegerField(primary_key='True', serialize=False)),
                ('name', models.CharField(max_length=70)),
                ('email_id', models.EmailField(max_length=100)),
                ('phone_number', models.IntegerField()),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('pin', models.CharField(max_length=6)),
                ('status', models.CharField(choices=[('Not Verified', 'Not Verified'), ('Verified', 'Verified'), ('Inactive', 'Inactive')], default='Not Verified', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('training_id', models.IntegerField(primary_key='True', serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('desc', models.CharField(max_length=100)),
                ('fees', models.IntegerField()),
                ('image', models.ImageField(default='', upload_to='training')),
            ],
        ),
        migrations.CreateModel(
            name='TrainingBooking',
            fields=[
                ('booking_id', models.IntegerField(primary_key='True', serialize=False)),
                ('pet_name', models.CharField(max_length=50)),
                ('pet_type', models.CharField(max_length=50)),
                ('pet_breed', models.CharField(max_length=50)),
                ('appo_date_time', models.DateTimeField()),
                ('appo_full_date_time', models.DateTimeField()),
                ('appo_status', models.CharField(max_length=15)),
                ('pp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('provider_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.provider')),
                ('training_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.training')),
            ],
        ),
        migrations.RemoveField(
            model_name='servicebooking',
            name='groomer_id',
        ),
        migrations.RemoveField(
            model_name='servicebooking',
            name='pp_id',
        ),
        migrations.RemoveField(
            model_name='servicebooking',
            name='service_id',
        ),
        migrations.AddField(
            model_name='vet',
            name='image',
            field=models.ImageField(default='', upload_to='vet'),
        ),
        migrations.AlterField(
            model_name='vetbooking',
            name='pp_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Groomer',
        ),
        migrations.DeleteModel(
            name='Petparent',
        ),
        migrations.DeleteModel(
            name='ServiceBooking',
        ),
        migrations.DeleteModel(
            name='Services',
        ),
        migrations.AddField(
            model_name='groomingbooking',
            name='provider_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.provider'),
        ),
    ]
