# Generated by Django 3.2.5 on 2022-06-15 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_auto_20220615_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='image',
            field=models.ImageField(default='', upload_to='provider'),
        ),
    ]
