# Generated by Django 3.2.5 on 2022-06-15 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_alter_grooming_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groomingbooking',
            name='appo_status',
            field=models.CharField(choices=[('Registered', 'Registered'), ('Confirmed', 'Confirmed'), ('Fullfilled', 'Fullfilled')], default='Registered', max_length=100),
        ),
        migrations.AlterField(
            model_name='groomingbooking',
            name='pet_breed',
            field=models.CharField(blank='True', max_length=50, null='True'),
        ),
        migrations.AlterField(
            model_name='groomingbooking',
            name='pet_name',
            field=models.CharField(blank='True', max_length=50, null='True'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='address',
            field=models.CharField(blank='True', max_length=100, null='True'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='city',
            field=models.CharField(blank='True', max_length=50, null='True'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='email_id',
            field=models.EmailField(max_length=100, unique='True'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='phone_number',
            field=models.CharField(max_length=10, unique='True'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='pin',
            field=models.CharField(blank='True', max_length=6, null='True'),
        ),
        migrations.AlterField(
            model_name='trainingbooking',
            name='appo_status',
            field=models.CharField(choices=[('Registered', 'Registered'), ('Confirmed', 'Confirmed'), ('Fullfilled', 'Fullfilled')], default='Registered', max_length=100),
        ),
        migrations.AlterField(
            model_name='trainingbooking',
            name='pet_breed',
            field=models.CharField(blank='True', max_length=50, null='True'),
        ),
        migrations.AlterField(
            model_name='trainingbooking',
            name='pet_name',
            field=models.CharField(blank='True', max_length=50, null='True'),
        ),
        migrations.AlterField(
            model_name='vet',
            name='address',
            field=models.CharField(blank='True', max_length=100, null='True'),
        ),
        migrations.AlterField(
            model_name='vet',
            name='city',
            field=models.CharField(blank='True', max_length=50, null='True'),
        ),
        migrations.AlterField(
            model_name='vet',
            name='email_id',
            field=models.EmailField(max_length=100, unique='True'),
        ),
        migrations.AlterField(
            model_name='vet',
            name='phone_number',
            field=models.CharField(max_length=10, unique='True'),
        ),
        migrations.AlterField(
            model_name='vet',
            name='pin',
            field=models.CharField(blank='True', max_length=6, null='True'),
        ),
        migrations.AlterField(
            model_name='vetbooking',
            name='appo_status',
            field=models.CharField(choices=[('Registered', 'Registered'), ('Confirmed', 'Confirmed'), ('Fullfilled', 'Fullfilled')], default='Registered', max_length=100),
        ),
    ]
